theme: minima
title: heerup.github.com
tagline: a blog
author: 
  name: Julian Kopka Heerup
  email: juliankopkaheerup@gmail.com
  github: heerup

exclude: ["README.md"]
timezone: Etc/UTC
  
# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true
